### ISSUE TITLE
Wrong error message shown in mustOnlyDependOn validators

### ISSUE THREAD

**Issue by JavierMF** [j6s/phparch#18]
Currently, when the mustOnlyDependOn validation fails, it shows and error like
`Component(A) must not depend on Component(B) but A/whatever depends on C/whatever`

while it should show something like
`Component(A) must only depend on Component(B) but A/whatever depends on C/whatever`

**Comment by j6s** [comment]
Seems like a copy&paste error. Thanks for fixing.
I'll tag a bugfix release with this fix so you'll be able to `composer update` soon

**Comment by JavierMF** [comment]
Thanks a lot.
