### ISSUE TITLE
Support symfony/finder 6

### ISSUE THREAD

**Issue by marc-mabe** [j6s/phparch#26]
```
Problem 1
- Root composer.json requires j6s/phparch ^3.1 -> satisfiable by j6s/phparch[3.1.0].
- j6s/phparch 3.1.0 requires symfony/finder ^4.1|^5.0 -> found symfony/finder[v4.1.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

**Comment by j6s** [comment]
Oh, I am not using symfony components 6 yet? I am sorry for this oversight. I'll check compatibility in the evening, but from what I remember from other projects, there are no real changes in `symfony/finder`

**Comment by j6s** [comment]
With version 3.1.1 of the library, phparch can be installed alongside / with `symfony/finder` 6.x

**Comment by marc-mabe** [comment]
Works thanks 👍
