### ISSUE TITLE
A simple check doesn't capture dependency

### ISSUE THREAD

**Issue by sergekukharev** [j6s/phparch#9]
I think this project is super useful and will have many companies. In my case, we have a monolithic application with many different projects inside that 70+ engineers are working together. To figure out how to break it in pieces, I need to understand dependencies and control them a little bit.

I've tried `phparch` today, but didn't manage to figure out how to use it. 

Here's my test:
```php
public function testCoreDoesNotHaveExternalDependencies(): void
    {
        $components = [
            'Core' => 'Core\\Accounting',
            'Desktop Bundle' => 'DesktopBundle'
        ];

        $architecture = new Architecture();
        $architecture->components($components);

        $architecture
            ->component('Core')
            ->mustNotDependOn('Desktop Bundle');


        (new PhpArch())
            ->fromDirectory(__DIR__ . '/../../src/Core/Accounting')
            ->validate($architecture)
            ->assertHasNoErrors();
    }

```

Inside of the accounting, I have a class that creates an instance of DesktopBundle\\Experiment, but the test passes. Any idea where should I dig? I'll of course contribute back if I'll find the issue.

**Comment by j6s** [comment]
Hi, thank you for checking out phparch.

On first look your configuration seems to be fine.
Can you confirm, that all classes being tested for are autoloadable?

Let me try to reproduce a minimal example of your issue to figure this out.

**Comment by j6s** [comment]
I have created a small test project in order to track the issue down.
While I cannot reproduce your issue you might be able to help me move things around in that repository in order to reproduce that.

https://github.com/j6s/phparch-test

**Comment by j6s** [comment]
Closed due to inactivity
